name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/publish.yml'

permissions:
  contents: read
  packages: write

jobs:
  publish-container-image:
    name: publish container image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build image
      run: podman build -t stockdb .

    - name: Podman login to ghcr
      run: echo "${{ github.token }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Publish version image
      run: |
        #STOCKDB_VERSION=$(podman run --rm stockdb /bin/stockd --version)
        STOCKDB_VERSION="${{ githhub.sha }}"
        podman tag stockdb ghcr.io/${{ github.repository }}/stockdb:${STOCKDB_VERSION}
        podman push ghcr.io/${{ github.repository }}/stockdb:${STOCKDB_VERSION}

    - name: Publish main branch
      if: github.ref == 'ref/head/main'
      run:
        podman tag stockdb ghcr.io/${{ github.repository }}/stockdb:main
        podman push ghcr.io/${{ github.repository }}/stockdb:main


