name: Validate
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: 1.24

permissions:
  contents: read

jobs:
  deps:
    #Apache License 2.0 from RunC
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: install go
      uses: actions/setup-go@v5
      with:
        go-version: "${{ env.GO_VERSION }}"
        check-latest: true
    - name: verify deps
      run: make verify-vendor
    - name: no toolchain in go.mod # See https://github.com/opencontainers/runc/pull/4717, https://github.com/dependabot/dependabot-core/issues/11933.
      run: |
        if grep -q '^toolchain ' go.mod; then echo "Error: go.mod must not have toolchain directive, please fix"; exit 1; fi

  build-container-image:
    name: Build container image
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: build image
      run: podman build -t stockdb .

    - name: verify image
      timeout-minutes: 1
      run: podman run --rm stockdb /bin/stockd --version
